FROM node:20-alpine

# Set work directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# In development mode, we don't need to copy project files
# as they will be mounted as a volume

# Expose port
EXPOSE 3000

# Default command is for development mode with hot-reloading
# The actual command will be provided in docker-compose.yml
CMD ["npm", "run", "dev"]