# Generated by Django 5.0.4 on 2025-06-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressphoto',
            name='body_part_tags',
            field=models.JSONField(default=list, help_text='List of body part tags'),
        ),
    ]
